// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MihrapPlak.DAL.Context;

#nullable disable

namespace MihrapPlak.DAL.Migrations
{
    [DbContext(typeof(MihrapPlakDBContext))]
    partial class MihrapPlakDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MihrapPlak.Models.Concrete.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("AlbumCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AlbumFiyati")
                        .HasColumnType("money");

                    b.Property<string>("AlbumSanatcisi_Grubu")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("IndirimOrani")
                        .HasColumnType("decimal (5,2)");

                    b.Property<bool>("Satistami")
                        .HasColumnType("bit");

                    b.HasKey("AlbumId");

                    b.ToTable("Albumler");
                });

            modelBuilder.Entity("MihrapPlak.Models.Concrete.AlbumUser", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("AlbumId", "KullaniciId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("AlbumKullanicilar");
                });

            modelBuilder.Entity("MihrapPlak.Models.Concrete.User", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.Property<string>("KullaniciSoyAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MihrapPlak.Models.Concrete.AlbumUser", b =>
                {
                    b.HasOne("MihrapPlak.Models.Concrete.Album", "Album")
                        .WithMany("Albumler")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MihrapPlak.Models.Concrete.User", "User")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MihrapPlak.Models.Concrete.Album", b =>
                {
                    b.Navigation("Albumler");
                });

            modelBuilder.Entity("MihrapPlak.Models.Concrete.User", b =>
                {
                    b.Navigation("Kullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
